export default {
  "login": "RuxinMa",
  "id": 140491381,
  "node_id": "U_kgDOCF-6dQ",
  "avatar_url": "https://avatars.githubusercontent.com/u/140491381?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/RuxinMa",
  "html_url": "https://github.com/RuxinMa",
  "followers_url": "https://api.github.com/users/RuxinMa/followers",
  "following_url": "https://api.github.com/users/RuxinMa/following{/other_user}",
  "gists_url": "https://api.github.com/users/RuxinMa/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/RuxinMa/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/RuxinMa/subscriptions",
  "organizations_url": "https://api.github.com/users/RuxinMa/orgs",
  "repos_url": "https://api.github.com/users/RuxinMa/repos",
  "events_url": "https://api.github.com/users/RuxinMa/events{/privacy}",
  "received_events_url": "https://api.github.com/users/RuxinMa/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Ruxin Ma",
  "company": "University of Adelaide",
  "blog": "https://ruxinma.netlify.app/",
  "location": "Adelaide",
  "email": 'allisonmrx610@gmail.com',
  "hireable": false,
  "bio": 'Happy Coding 😊',
  "twitter_username": 'allison0610',
  "public_repos": 20,
  "public_gists": 3,
  "followers": 23,
  "following": 56,
  "created_at": "2023-07-25T07:52:04Z",
  "updated_at": "2024-03-31T05:13:23Z"
  }
